"""Add deleted_at and construction_year

Revision ID: 136613429a05
Revises: 
Create Date: 2026-02-03 10:27:36.219549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136613429a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('property_type', sa.String(length=100), nullable=False, comment='Type: flerbostadshus, villa, kontor, etc.'),
    sa.Column('designation', sa.String(length=255), nullable=False, comment='Fastighetsbeteckning (unique identifier)'),
    sa.Column('owner', sa.String(length=255), nullable=True, comment='Property owner name or organization'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='Street address'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal code'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('num_apartments', sa.Integer(), nullable=True, comment='Number of apartments/lägenheter'),
    sa.Column('num_premises', sa.Integer(), nullable=True, comment='Number of commercial premises/lokaler'),
    sa.Column('construction_year', sa.Integer(), nullable=True, comment='Year when building was constructed'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about the property'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_properties_designation'), ['designation'], unique=False)

    op.create_table('standard_defects',
    sa.Column('code', sa.String(length=30), nullable=False, comment='Unique defect code (e.g., VF01)'),
    sa.Column('title', sa.String(length=120), nullable=False, comment='Short title/summary'),
    sa.Column('description', sa.Text(), nullable=False, comment='Standard description text'),
    sa.Column('remedy', sa.Text(), nullable=True, comment='Standard remedy text'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='defectseverity'), nullable=False, comment='Default severity level'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether this template is active/available'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Category for grouping (e.g., 'Ventilation', 'Plumbing')"),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_defects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_defects_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_standard_defects_code'), ['code'], unique=True)

    op.create_table('sync_logs',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False, comment='Idempotency key from X-Idempotency-Key header'),
    sa.Column('device_id', sa.String(length=255), nullable=False, comment='Client device identifier'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who performed the operation'),
    sa.Column('operation_id', sa.String(length=255), nullable=False, comment='Client-generated operation ID'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Entity type (inspection, apartment, defect, etc.)'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='Action: create, update, delete'),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='Client-generated UUID for the entity'),
    sa.Column('server_id', sa.Integer(), nullable=True, comment='Server-assigned ID after processing'),
    sa.Column('request_body', sa.JSON(), nullable=True, comment='Original request body (for replay/debugging)'),
    sa.Column('response_body', sa.JSON(), nullable=True, comment='Response returned to client'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP status code'),
    sa.Column('processed_at', sa.DateTime(), nullable=False, comment='When the operation was processed'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='When this log entry can be cleaned up'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index('idx_sync_log_device_user', ['device_id', 'user_id'], unique=False)
        batch_op.create_index('idx_sync_log_entity', ['entity_type', 'client_id'], unique=False)
        batch_op.create_index('idx_sync_log_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_logs_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address for login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Full name of the inspector'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='User role: admin, inspector, viewer'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company or organization name'),
    sa.Column('certification_org', sa.String(length=100), nullable=True, comment='Certifieringsorgan (SP, SITAC, etc.)'),
    sa.Column('certification_number', sa.String(length=100), nullable=True, comment='Certifieringsnummer'),
    sa.Column('certification_valid_until', sa.String(length=50), nullable=True, comment='Giltighetstid för certifiering (YYYY-MM-DD eller text)'),
    sa.Column('competence', sa.Text(), nullable=True, comment='Behörighet/kompetensområde (kan vara längre text)'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Contact phone number'),
    sa.Column('signature_image_id', sa.String(length=255), nullable=True, comment='Reference to signature image (stored in storage service)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('inspections',
    sa.Column('property_id', sa.Integer(), nullable=False, comment='Property being inspected'),
    sa.Column('inspector_id', sa.Integer(), nullable=True, comment='Inspector performing the inspection'),
    sa.Column('date', sa.Date(), nullable=False, comment='Inspection date'),
    sa.Column('active_time_seconds', sa.Integer(), nullable=False, comment='Active inspection time in seconds (from timer)'),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', 'ARCHIVED', name='inspectionstatus'), nullable=False, comment='Inspection status: draft, final, archived'),
    sa.Column('notes', sa.String(length=2000), nullable=True, comment='General notes about the inspection'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspections_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_status'), ['status'], unique=False)

    op.create_table('apartments',
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='Inspection this apartment belongs to'),
    sa.Column('apartment_number', sa.String(length=20), nullable=False, comment='Apartment number (e.g., 1201, A12, 12B)'),
    sa.Column('rooms', sa.JSON(), nullable=False, comment='Array of rooms: [{index: int, type: string}, ...]'),
    sa.Column('notes', sa.String(length=1000), nullable=True, comment='Additional notes about the apartment'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apartments_apartment_number'), ['apartment_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_apartments_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_apartments_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('measurements',
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='Inspection this measurement belongs to'),
    sa.Column('type', sa.Enum('FLODE', 'TRYCK', 'TEMP', 'CO2', 'FUKT', 'LJUD', 'OKAND', name='measurementtype'), nullable=False, comment='Type of measurement'),
    sa.Column('value', sa.Float(), nullable=False, comment='Measured value'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Unit of measurement (e.g., l/s, Pa, °C)'),
    sa.Column('apartment_number', sa.String(length=20), nullable=True, comment='Apartment number if measurement is specific to apartment'),
    sa.Column('sort_key', sa.String(length=60), nullable=True, comment='Custom sort key for ordering measurements'),
    sa.Column('notes', sa.String(length=300), nullable=True, comment='Additional notes about the measurement'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_apartment_number'), ['apartment_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_measurements_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_type'), ['type'], unique=False)

    op.create_table('pdf_versions',
    sa.Column('inspection_id', sa.Integer(), nullable=False, comment='Inspection this PDF belongs to'),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True, comment='User who created this PDF version'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Sequential version number (1, 2, 3, ...)'),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='pdfstatus'), nullable=False, comment='Status: draft or final'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='Key/path in storage service'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Generated filename'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA256 checksum for integrity'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_versions_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pdf_versions_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_versions_storage_key'), ['storage_key'], unique=True)

    op.create_table('defects',
    sa.Column('apartment_id', sa.Integer(), nullable=False, comment='Apartment where defect was found'),
    sa.Column('room_index', sa.Integer(), nullable=False, comment='Room index within apartment (0-based)'),
    sa.Column('code', sa.String(length=30), nullable=True, comment='Standard defect code (e.g., VF01)'),
    sa.Column('title', sa.String(length=120), nullable=True, comment='Short title/summary'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the defect'),
    sa.Column('remedy', sa.Text(), nullable=True, comment='Recommended remedy/action'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='defectseverity'), nullable=False, comment='Severity: low, medium, high'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_apartment_id'), ['apartment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_client_id'), ['client_id'], unique=True)

    op.create_table('images',
    sa.Column('defect_id', sa.Integer(), nullable=False, comment='Defect this image belongs to'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Sanitized filename'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='Key/path in storage service (local or S3)'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type (e.g., image/jpeg, image/png)'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA256 checksum for integrity'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Image width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Image height in pixels'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True, comment='UUID generated by client for offline-first sync'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='Version number for optimistic locking'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when entity was last updated (UTC)'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_images_defect_id'), ['defect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_storage_key'), ['storage_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_storage_key'))
        batch_op.drop_index(batch_op.f('ix_images_defect_id'))
        batch_op.drop_index(batch_op.f('ix_images_client_id'))

    op.drop_table('images')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_client_id'))
        batch_op.drop_index(batch_op.f('ix_defects_apartment_id'))

    op.drop_table('defects')
    with op.batch_alter_table('pdf_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_versions_storage_key'))
        batch_op.drop_index(batch_op.f('ix_pdf_versions_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_versions_client_id'))

    op.drop_table('pdf_versions')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_type'))
        batch_op.drop_index(batch_op.f('ix_measurements_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_measurements_client_id'))
        batch_op.drop_index(batch_op.f('ix_measurements_apartment_number'))

    op.drop_table('measurements')
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apartments_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_apartments_client_id'))
        batch_op.drop_index(batch_op.f('ix_apartments_apartment_number'))

    op.drop_table('apartments')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_inspections_property_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_date'))
        batch_op.drop_index(batch_op.f('ix_inspections_client_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_client_id'))

    op.drop_table('users')
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_operation_id'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_expires_at'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_device_id'))
        batch_op.drop_index('idx_sync_log_expires')
        batch_op.drop_index('idx_sync_log_entity')
        batch_op.drop_index('idx_sync_log_device_user')

    op.drop_table('sync_logs')
    with op.batch_alter_table('standard_defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_defects_code'))
        batch_op.drop_index(batch_op.f('ix_standard_defects_client_id'))
        batch_op.drop_index(batch_op.f('ix_standard_defects_category'))

    op.drop_table('standard_defects')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_designation'))
        batch_op.drop_index(batch_op.f('ix_properties_client_id'))

    op.drop_table('properties')
    # ### end Alembic commands ###
